baseURL = "https://synbiohub.github.io"
languageCode = "en-us"
title = "SynBioHub-Documentation"
theme = "ace-documentation"
Copyright = "© SynBioHub 2020"
canonifyurls = true

[params]

menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
disableSearch = true 
hideHUGOSupport = false
[[menu.main]]  # here are the buttons on the menu
name = "Main Page" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "_index.md"
pre = "<br />"
url = "/"
[[menu.main]]
name = "About SynBioHub"
weight = 100
identifier = "AboutSynBioHub" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/AboutSynBioHub"
[[menu.main]]
name = "API Documentation"
identifier = "APIDocumentation" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/APIDocumentation"
weight = 70
[[menu.main]]
name = "References"
weight = 40
identifier = "References" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/References"
[[menu.main]]
name = "Installation"
weight = 90
identifier = "Installation" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/Installation"
[[menu.main]]
name = "Reporting Errors"
weight = 85
identifier = "ReportingErrors" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/ReportingErrors"
[[menu.main]]
name = "Plugins"
weight = 60
identifier = "Plugins" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/Plugins"
[[menu.main]]
name = "Troubleshooting"
weight = 50
identifier = "T&R" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/T&R"
[[menu.main]]
name = "User Documentation"
weight = 100
identifier = "UserDocumentation" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/UserDocumentation"
[[menu.main]]
name = "Setup"
weight = 80
identifier = "Setup" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/Setup"


[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"



